target: docroot
build_file: build.make
subtrees:
  minimal_ci:
    path: docroot/profiles/minimal_ci
    uri: 'https://github.com/bryanhirsch/minimal_ci.git'
    branch: 7.x-1.x
    squash: false
commands:
  # @todo Add logic to settings.php to make it so we don't have to comment out
  # the next line.
  # - 'rm -rf docroot/sites/default; cd docroot/sites; ln -s ../../symlink-these/default default'
  - 'rm -rf docroot/.htaccess; cd docroot/; ln -s ../symlink-these/.htaccess .htaccess'
  - 'rm -rf docroot/robots.txt; cd docroot/; ln -s ../symlink-these/robots.txt robots.txt'
